//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VajaElektrika
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meritve
    {
        public int ZapisID { get; set; }
        public Nullable<System.DateTime> ZapisČas { get; set; }
        public Nullable<float> V1 { get; set; }
        public Nullable<float> A1 { get; set; }
        public Nullable<float> kW1 { get; set; }
        public Nullable<float> V2 { get; set; }
        public Nullable<float> A2 { get; set; }
        public Nullable<float> kW2 { get; set; }
        public Nullable<float> V3 { get; set; }
        public Nullable<float> A3 { get; set; }
        public Nullable<float> kW3 { get; set; }
    }
}
